export const NOTE_APPEARANCE = {
  fonts: {
    body: 'Calibri',
    heading: 'Calibri Light',
  },
  docx: {
    sizes: {
      title: 32,
      heading1: 28,
      heading2: 24,
      body: 22,
      small: 20,
    },
    spacing: {
      beforeSection: 240,
      afterSection: 120,
      beforeSubsection: 120,
      afterSubsection: 80,
      beforeParagraph: 40,
      afterParagraph: 40,
      lineSpacing: 240,
    },
  },
  colors: {
    ink: '#111827',
    inkSoft: '#1f2937',
    inkMuted: '#374151',
    muted: '#4b5563',
    mutedSoft: '#6b7280',
    accent: '#009a44',
    accentDark: '#007a35',
    white: '#ffffff',
    tableHeader: '#1f2937',
    tableStripe: '#f8fafc',
    borderSoft: 'rgba(15, 23, 42, 0.08)',
    borderInput: 'rgba(15, 23, 42, 0.12)',
    borderStrong: 'rgba(203, 213, 225, 0.95)',
    borderTable: 'rgba(226, 232, 240, 0.95)',
    successBg: 'rgba(236, 253, 245, 0.9)',
    successBorder: 'rgba(0, 122, 53, 0.14)',
    warningBg: 'rgba(255, 251, 235, 0.95)',
    warningBorder: 'rgba(253, 230, 138, 0.95)',
    pageHeaderBg: 'linear-gradient(180deg, rgba(252, 252, 252, 0.98), rgba(248, 250, 252, 0.96))',
    pageBg:
      'linear-gradient(180deg, rgba(255, 255, 255, 0.98), rgba(252, 252, 251, 0.98)), repeating-linear-gradient(180deg, rgba(14, 24, 33, 0.015), rgba(14, 24, 33, 0.015) 1px, transparent 1px, transparent 34px)',
    modalBg: '#eef2f4',
    modalToolbarBg: 'linear-gradient(180deg, rgba(18, 18, 18, 0.96), rgba(58, 58, 58, 0.96))',
    sheetBg: 'rgba(255, 255, 255, 0.96)',
    blockBg: '#fcfcfd',
    metricBg: '#ffffff',
    signatureBg: 'linear-gradient(180deg, rgba(240, 253, 244, 0.95), rgba(248, 250, 252, 0.95))',
    overlayBg: 'rgba(15, 23, 42, 0.52)',
  },
  radii: {
    shell: '22px',
    sheet: '18px',
    table: '16px',
    block: '14px',
    metric: '12px',
    button: '14px',
    pill: '999px',
  },
  shadows: {
    modal: '0 36px 90px rgba(15, 23, 42, 0.28)',
    page: '0 24px 48px rgba(15, 23, 42, 0.08), 0 4px 12px rgba(15, 23, 42, 0.05)',
    sheet: '0 14px 30px rgba(15, 23, 42, 0.08)',
  },
} as const;

function serializeCssVars(vars: Record<string, string>): string {
  return Object.entries(vars)
    .map(([key, value]) => `${key}: ${value}`)
    .join('; ');
}

export function buildNoteCssVars(): string {
  return serializeCssVars({
    '--note-font-body': NOTE_APPEARANCE.fonts.body,
    '--note-font-heading': NOTE_APPEARANCE.fonts.heading,
    '--note-ink': NOTE_APPEARANCE.colors.ink,
    '--note-ink-soft': NOTE_APPEARANCE.colors.inkSoft,
    '--note-ink-muted': NOTE_APPEARANCE.colors.inkMuted,
    '--note-muted': NOTE_APPEARANCE.colors.muted,
    '--note-muted-soft': NOTE_APPEARANCE.colors.mutedSoft,
    '--note-accent': NOTE_APPEARANCE.colors.accent,
    '--note-accent-dark': NOTE_APPEARANCE.colors.accentDark,
    '--note-white': NOTE_APPEARANCE.colors.white,
    '--note-table-header': NOTE_APPEARANCE.colors.tableHeader,
    '--note-table-stripe': NOTE_APPEARANCE.colors.tableStripe,
    '--note-border-soft': NOTE_APPEARANCE.colors.borderSoft,
    '--note-border-input': NOTE_APPEARANCE.colors.borderInput,
    '--note-border-strong': NOTE_APPEARANCE.colors.borderStrong,
    '--note-border-table': NOTE_APPEARANCE.colors.borderTable,
    '--note-success-bg': NOTE_APPEARANCE.colors.successBg,
    '--note-success-border': NOTE_APPEARANCE.colors.successBorder,
    '--note-warning-bg': NOTE_APPEARANCE.colors.warningBg,
    '--note-warning-border': NOTE_APPEARANCE.colors.warningBorder,
    '--note-page-bg': NOTE_APPEARANCE.colors.pageBg,
    '--note-page-header-bg': NOTE_APPEARANCE.colors.pageHeaderBg,
    '--note-modal-bg': NOTE_APPEARANCE.colors.modalBg,
    '--note-modal-toolbar-bg': NOTE_APPEARANCE.colors.modalToolbarBg,
    '--note-sheet-bg': NOTE_APPEARANCE.colors.sheetBg,
    '--note-block-bg': NOTE_APPEARANCE.colors.blockBg,
    '--note-metric-bg': NOTE_APPEARANCE.colors.metricBg,
    '--note-signature-bg': NOTE_APPEARANCE.colors.signatureBg,
    '--note-overlay-bg': NOTE_APPEARANCE.colors.overlayBg,
    '--note-radius-shell': NOTE_APPEARANCE.radii.shell,
    '--note-radius-sheet': NOTE_APPEARANCE.radii.sheet,
    '--note-radius-table': NOTE_APPEARANCE.radii.table,
    '--note-radius-block': NOTE_APPEARANCE.radii.block,
    '--note-radius-metric': NOTE_APPEARANCE.radii.metric,
    '--note-radius-button': NOTE_APPEARANCE.radii.button,
    '--note-radius-pill': NOTE_APPEARANCE.radii.pill,
    '--note-shadow-modal': NOTE_APPEARANCE.shadows.modal,
    '--note-shadow-page': NOTE_APPEARANCE.shadows.page,
    '--note-shadow-sheet': NOTE_APPEARANCE.shadows.sheet,
  });
}
